# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        Lord Hope's Blog
subtitle:     Talk  is  cheap,  write  here.
description:  //TODO
keywords:     blog
language:     "en"

baseurl:      "" # the subpath of your site, e.g. /blog
url:          "http://i77.io/blog"
permalink:    /:categories/:title
cover:        /assets/img/home_cover.jpg

# Build settings
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from